version: '3'

services:
  ##########################################
  # Overrides for oada-core services:
  ##########################################

  # Add ourselves to yarn to do yarn install
  yarn:
    volumes:
      - ./services-available/trellis-notifications:/code/trellis-notifications

  # Add ourselves to admin container:
  admin:
    volumes:
      - ./services-available/trellis-notifications:/code/trellis-notifications

  ###############################################
  # This service's definition:
  ###############################################
  trellis-notifications:
    build:
      context: ./services-available/trellis-notifications
    container_name: trellis-notifications
    restart: always
    networks:
      - http_net
      - startup_net
    volumes:
      - ./services-available/trellis-notifications:/code/trellis-notifications
      - ./oada-core/libs:/code/libs
      - ./oada-srvc-docker-config.js:/oada-srvc-docker-config.js
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG=${DEBUG:-"trellis-notifications:info,*warn*,*error*"}
      - domain
      - token
